//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisionSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public int Order_Id { get; set; }
        public string expense_name { get; set; }
        public string date { get; set; }
        public string month { get; set; }
        public string bill_no { get; set; }
        public Nullable<int> amount { get; set; }
        public string img { get; set; }
    }
}
